### ISSUE TITLE
Create Dashboard Page from Wireframe

### ISSUE THREAD

**Issue by paskantishubham** [dc-release/dc-portal#13]
Develop a Dashboard for DC-Portal by referring to [Wireframe](https://github.com/dc-release/dc-portal/blob/v1beta/Portal%20UX%20Artifacts/WebPages/Dashboard%20-%20Customer%402x.png).

**Comment by ayasuda-ge** [comment]
Also please provide the content of this tracker. The descrition is blank. @paskantishubham

**Comment by ayasuda-ge** [comment]
what is the wireframe? could you be specific in this issue? @paskantishubham

**Comment by paskantishubham** [comment]
> what is the wireframe? could you be specific in this issue? @paskantishubham

@ayasuda-ge I mentioned the wireframe link for better understanding. Please review it
