### ISSUE TITLE
Create Service(Thread Connect) Page

### ISSUE THREAD

**Issue by paskantishubham** [dc-release/dc-portal#14]
Develop a service page i.e Thread connect, should redirect onclick from dashboard

Referring to [Wireframe](https://github.com/dc-release/dc-portal/blob/v1beta/Portal%20UX%20Artifacts/WebPages/Dashboard%20-%20Customer%20%E2%80%93%20DrillDown%20Subscription%20-%20ThreadConnect%402x.png)

**Comment by ayasuda-ge** [comment]
@paskantishubham please give content of this empty tracker.

**Comment by ayasuda-ge** [comment]
close #21
