### ISSUE TITLE
Redesign footer according to GE standards

### ISSUE THREAD

**Issue by paskantishubham** [dc-release/dc-portal#32]
Current footer which has copyright and social media links, should be redesigned according to [GE's](https://www.ge.com/) footer.

**Comment by Pagrawa8** [comment]
@paskantishubham @ayasuda-ge - A feedback from yesterday's portal rhythm was that the footer looks off, besides this portal is not for external customers (all internal to GE) so we do not see a need to add Fb, twitter etc.

It may be beneficial to include Yammer, chat (To be built). These can be added on the left nav, the way it was before to save real estate and a clean look.

**Comment by ayasuda-ge** [comment]
merged and closed #33
