### ISSUE TITLE
Need Globalscape and Informatica - Favicons or Logos (lossless) eg:svg

### ISSUE THREAD

**Issue by Pagrawa8** [dc-release/dc-portal#41]
@awaisbajwaml Kindly provide Globalscape and Informatica - Favicons or Logos (lossless) eg:svg

**Comment by awaisbajwaml** [comment]
@Pagrawa8  can you please provide some more details on Favicons or Logos what is lossless? 

I can help you in GLobalscape but for Informatica please contact someone from Informatica team

**Comment by Ripu-D-Singh** [comment]
@awaisbajwaml , Lossless formats are formats like svg/ ai which we can scale up or down basis our needs without it getting pixelated.

We need the GS logo and favicon(generally a small icon tied to any product)

**Comment by ayasuda-ge** [comment]
@awaisbajwaml please PR the v1beta for the design materials, if any. Thanks

**Comment by awaisbajwaml** [comment]
latest update on this, this request has been submitted to Craig

**Comment by ayasuda-ge** [comment]
Close #51
