### ISSUE TITLE
Carousal & Engagement Request Form Implemention

### ISSUE THREAD

**Issue by paskantishubham** [dc-release/dc-portal#45]
Add carousal on services cards and create a form similar to [this](https://app.smartsheet.com/b/form/74f7e5c706d04aca841df70661a5631b) for New Engagement Request.

**Comment by Pagrawa8** [comment]
As mentioned by Ripu, apply the resized logos for the products

**Comment by ayasuda-ge** [comment]
UI will not invoke HTTP call directly to any endpoint beyond the backend. Any endpoints such as smartsheet, will require proper integration via OIDC. @paskantishubham  @Pagrawa8  @Ripu-D-Singh
