### ISSUE TITLE
 - Build failing

### ISSUE THREAD

**Issue by ayasuda-ge** [dc-release/dc-portal#48]
The build has been consistently [failing on npm test/jasmin](https://github.com/dc-release/dc-portal/runs/3078808783?check_suite_focus=true#step:3:36) that requires some attentions.

**Comment by paskantishubham** [comment]
@ayasuda-ge I fixed build. Please check latest build.

**Comment by ayasuda-ge** [comment]
> @ayasuda-ge I fixed build. Please check latest build.

please tag a working PR to support the fix.

**Comment by paskantishubham** [comment]
@ayasuda-ge tagged PR to support this issue.
